---
title: Centreer tekst horizontaal en verticaal
hero_image: images/banner.png
description: Centreer tekst horizontaal en verticaal.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Centreer tekst horizontaal en verticaal
