title: Center text horizontally and vertically
hero_image: images/banner.png
description: Center text horizontally and vertically.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Center text horizontally and vertically
