title: Centre text horizontally and vertically
hero_image: images/banner.png
description: Centre text horizontally and vertically.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Centre text horizontally and vertically
